### ISSUE TITLE
proveL2MessageInclusion reverted "xx" code

### ISSUE THREAD

**Issue by cogiakk54** [matter-labs/era-contracts#10]
![image](https://github.com/matter-labs/era-contracts/assets/44942581/d2188854-a642-455f-a8ed-376ea46c85aa)
zksync transaction: https://goerli.explorer.zksync.io/tx/0x6b43b036ef12cbd1d1ea99985b351c8d59d7cb22df2cbd210c2cbee48e56918b
I build an ERC20 bridge, but there are some messages that cannot authenticate messages from L2

here is params:
_blockNumber : 116164
_index: 1
_message: {txNumberInBlock: 562,sender: '0x1A09Bb36D7ed3eA5B1E4a53524586b45A63b503d',data: '0x11a2ccc1bfdf0d833e0be831646deeccf5a83da059f75b9e41211b38e33fea004c6767b0f150ede68e1e1d450000000000000000000000000000000000000000000000000de0b6b3a7640000' }
_proof: 0x926feac01291258985ffe1dc39fff171a7322f1743dfb59423bdf52104b34abd,0x82c55589ad70ca6e76c54a9b040ac73c566e788f76a205b10cabe4eb8a6ff4b0,0xe3697c7f33c31a9b0f0aeb8542287d0d21e8c4cf82163d0c44c7a98aa11aa111,0x199cc5812543ddceeddd0fc82807646a4899444240db2c0d2f20c3cceb5f51fa,0xe4733f281f18ba3ea8775dd62d2fcd84011c8c938f16ea5790fd29a03bf8db89,0x1798a1fd9c8fbb818c98cff190daa7cc10b6e5ac9716b4a2649f7c2ebcef2272,0x66d7c5983afe44cf15ea8cf565b34c6c31ff0cb4dd744524f7842b942d08770d,0xb04e5ee349086985f74b73971ce9dfe76bbed95c84906c5dffd96504e1e5396c,0xac506ecb5465659b3a927143f6d724f91d8d9c4bdb2463aee111d9aa869874db

**Comment by SensationalShubham** [comment]
Can i work on this issue?
